### ISSUE TITLE
[Bug] Broken link on /salary-transparency

### ISSUE THREAD

**Issue by theecrit** [theecrit/contentandux#48]
**What were you trying to do when you encountered the bug?**
Clicked on "Please use our recruiter submission form."

**Describe what went wrong:**
Did not open link.

**Fix:**
Re-link to https://bit.ly/content-jobs-recruiter-submission

**Comment by namit-chandwani** [comment]
Hey, I'd like to work on this issue!

**Comment by theecrit** [comment]
Thanks for taking care of this, @namit-chandwani! I've approved the pull request but just need you to verify your commit signature (see the link I posted on the PR for details). I _think_ it's pretty straightforward.

**Comment by namit-chandwani** [comment]
Okay, I'll have a look and let you know once done.
